admin_admin:
    resource: "@AdminAdminBundle/Resources/config/routing.yml"
    prefix:   /

faq_survey:
    resource: "@FAQSurveyBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
